ApiException 단일 방식에서 BadRequest, InternalServer로 분리
gamemuncheol/gamemuncheol-api pull request #102
Opened 2024-05-22 17:16 UTC by rookedsysc

## Related Issue

Related to : #101 

## Goal 

ApiException 단일 방식에서 BadRequest, InternalServer로 분리 

## Added Content 

- TokenProvider 삭제(TokenHelper와 중복)
- ExceptionHandler 삭제(존재하는 이유 없음)
- ApiException 삭제 -> BadRequestException, InternalServerErrorException으로 분리

2024-05-22 23:16 UTC, slbin-park requested changes
400과 404를 분리하는게 러떨까요 다 400으로 내려주는것 같네요

2024-05-22 23:16 UTC, slbin-park commented on src/main/java/com/gamemoonchul/application/CommentService.java
> +        throw new BadRequestException(MemberStatus.NOT_AUTHORIZED_MEMBER);
이건 401에러 아닌가요?

2024-05-22 23:16 UTC, slbin-park commented on src/main/java/com/gamemoonchul/application/MemberService.java
> +            throw new BadRequestException(MemberStatus.ALREADY_EXIST_NICKNAME);
충돌은 409였나 있을겁니다

2024-05-22 23:16 UTC, slbin-park commented on src/main/java/com/gamemoonchul/application/converter/CommentConverter.java
> +                            return new BadRequestException(PostStatus.POST_NOT_FOUND);
notfound는 404 낫파운드 익셉션이 어떤가요

2024-05-22 23:20 UTC, slbin-park commented on src/main/java/com/gamemoonchul/config/jwt/MemberSessionResolver.java
> +                    return new BadRequestException(MemberStatus.MEMBER_NOT_FOUND);
not found는 404로 새로 만드시죠

2024-05-23 11:13 UTC, rookedsysc commented on src/main/java/com/gamemoonchul/application/CommentService.java
> +        throw new BadRequestException(MemberStatus.NOT_AUTHORIZED_MEMBER);
[Commit](02996b6b660a4449cd14ca6ae4baea51a2934f66)에서 수정했습니다

2024-05-23 11:14 UTC, rookedsysc commented on src/main/java/com/gamemoonchul/application/converter/CommentConverter.java
> +                            return new BadRequestException(PostStatus.POST_NOT_FOUND);
[Commit](https://github.com/gamemuncheol/gamemuncheol-api/pull/102/commits/02996b6b660a4449cd14ca6ae4baea51a2934f66)에서 수정했습니다.

2024-05-23 11:14 UTC, rookedsysc commented on src/main/java/com/gamemoonchul/config/jwt/MemberSessionResolver.java
> +                    return new BadRequestException(MemberStatus.MEMBER_NOT_FOUND);
[Commit](https://github.com/gamemuncheol/gamemuncheol-api/pull/102/commits/02996b6b660a4449cd14ca6ae4baea51a2934f66)에서 수정했습니다.

2024-05-23 11:17 UTC, slbin-park commented on src/main/java/com/gamemoonchul/application/S3Service.java
> +                throw new MethodNotAllowedException(S3Status.INVALID_FILETYPE);
이거까진 안해도 될것같고 400 badreqeust 정도면 될것 같아요

2024-05-23 11:17 UTC, slbin-park commented on src/main/java/com/gamemoonchul/config/jwt/TokenHelper.java
> +                throw new MethodNotAllowedException(JwtStatus.TOKEN_TYPE_NOT_MATCH);
이부분은 굳이 따지고보면 잘못 요청한거기 때문에 400 badRequest쪽이 아닐까요

2024-05-23 11:46 UTC, rookedsysc commented on src/main/java/com/gamemoonchul/application/S3Service.java
> +                throw new MethodNotAllowedException(S3Status.INVALID_FILETYPE);
https://github.com/gamemuncheol/gamemuncheol-api/pull/102/commits/42ccd79b684e2631029259b5162db45ed3c713c7 에서 수정했습니다.

2024-05-23 11:46 UTC, rookedsysc commented on src/main/java/com/gamemoonchul/config/jwt/TokenHelper.java
> +                throw new MethodNotAllowedException(JwtStatus.TOKEN_TYPE_NOT_MATCH);
https://github.com/gamemuncheol/gamemuncheol-api/pull/102/commits/42ccd79b684e2631029259b5162db45ed3c713c7 에서 수정했습니다.

2024-05-23 11:46 UTC, merged