게시판 최신순 정렬 API 개발
gamemuncheol/gamemuncheol-api pull request #76
Opened 2024-04-23 06:32 UTC by rookedsysc

## Related Issue

Related to : #75 

## Goal 

게시판 최신순 정렬 API 개발

## Added Content 

- findAllByOrderByCreatedAt Method
- Test 코드 작성
- "/open-api/post/page/new" API

2024-04-25 10:36 UTC, slbin-park requested changes

2024-04-25 10:36 UTC, slbin-park commented on src/main/java/com/gamemoonchul/application/PostOpenApiService.java
> +@RequiredArgsConstructor
서비스레이어에 기본으로 트랜잭션 리드온리 붙입시다

2024-04-25 10:36 UTC, slbin-park commented on src/main/java/com/gamemoonchul/domain/entity/Post.java
> +    @JsonIgnore
이건 왜들어간걸까요?

2024-04-25 10:36 UTC, slbin-park commented on src/main/java/com/gamemoonchul/infrastructure/web/PostOpenApiController.java
> +@RestControllerWithEnvelopPattern
이거 간단하게 설명해주실수있을까요

2024-04-25 10:36 UTC, slbin-park commented on src/main/java/com/gamemoonchul/infrastructure/web/PostOpenApiController.java
> +            @RequestParam(value = "page", defaultValue = "0") int page,
벨리데이션 -1같은 값 같은게 들어가도 처리가 되는걸까요?

2024-04-25 10:36 UTC, slbin-park commented on src/test/java/com/gamemoonchul/application/PostOpenApiServiceTest.java
> +        for (int i = 1; i < searchedPost.size(); i++) {
assertions 랑 .map 람다로도 처리가 가능해보입니다

2024-04-25 10:36 UTC, slbin-park commented on src/test/java/com/gamemoonchul/application/PostOpenApiServiceTest.java
> +@Transactional
서비스레이어 테스트에는 트랜잭션이 필요없지않나요? 어차피 레포지토리는 모킹할텐데

2024-04-25 10:36 UTC, slbin-park commented on src/test/java/com/gamemoonchul/application/PostOpenApiServiceTest.java
> +    private PostRepository postRepository;
서비스레이어 테스트는 레포지토리를 모킹하는게 좋을것 같네요 다른데 의존성이 생기는거라

2024-04-25 10:36 UTC, slbin-park commented on src/test/java/com/gamemoonchul/domain/entity/PostDummy.java
> +    public static Post createPost(String value) {
이거는 파일을 따로빼서 mock 클래스로 정의하는게 어떤가요?

2024-04-25 10:37 UTC, slbin-park commented on src/main/java/com/gamemoonchul/domain/entity/Post.java
> +    @JsonIgnore
필드를 빼서 리턴할 일이 생기면 새로운 dto를 만드는게 좋지않을까요?

2024-04-26 16:30 UTC, rookedsysc commented on src/main/java/com/gamemoonchul/application/PostOpenApiService.java
> +@RequiredArgsConstructor
[8069df4](https://github.com/gamemuncheol/gamemuncheol-api/pull/76/commits/8069df46dad431ad5b00230bf77c1db1bd1ea21b) 에서 수정했습니다.

2024-04-26 16:31 UTC, rookedsysc commented on src/main/java/com/gamemoonchul/domain/entity/Post.java
> +    @JsonIgnore
순환참조가 일어나는 버그를 방지하기 위해서 들어갔습니다. 근본적인 문제인 DTO가 아닌 Entity를 반환하는 코드로 변경해서 수정했습니다. [4e7a4d3](https://github.com/gamemuncheol/gamemuncheol-api/pull/76/commits/4e7a4d3f6f352985c9d3045252dd17a6031fd9a3)

2024-04-26 18:02 UTC, rookedsysc commented on src/main/java/com/gamemoonchul/infrastructure/web/PostOpenApiController.java
> +@RestControllerWithEnvelopPattern
봉투패턴을 적용해놓은 RestController 입니다. 인터페이스는 [여기에](https://github.com/gamemuncheol/gamemuncheol-api/blob/bdcd6dbada21b86b2afa37d3d3e853289c53e435/src/main/java/com/gamemoonchul/infrastructure/web/common/RestControllerWithEnvelopPattern.java#L3) 인터페이스의 동작은 [여기에](https://github.com/gamemuncheol/gamemuncheol-api/blob/bdcd6dbada21b86b2afa37d3d3e853289c53e435/src/main/java/com/gamemoonchul/infrastructure/web/common/ApiResponseWrappingResponseBodyAdvisor.java#L15) 저장되어 있는데요.

Response를 성공/실패에 관계 없이 

```json
{
    success : "" ,
    data : "" ,
    status : "" 
}
```

 처럼 주기 위해서 Controller에 RestController Annotation 대신 사용됩니다.

2024-04-26 18:25 UTC, rookedsysc commented on src/main/java/com/gamemoonchul/infrastructure/web/PostOpenApiController.java
> +            @RequestParam(value = "page", defaultValue = "0") int page,
컨트롤러 부분에서 Exception이 발생하게 되는데 PageRequest.of 부분을 타고 들어가면 

```java
	public AbstractPageRequest(int pageNumber, int pageSize) {

		if (pageNumber < 0) {
			throw new IllegalArgumentException("Page index must not be less than zero");
		}

		if (pageSize < 1) {
			throw new IllegalArgumentException("Page size must not be less than one");
		}

		this.pageNumber = pageNumber;
		this.pageSize = pageSize;
	}
```

부분에서 예외를 처리해주고 있는 것을 알 수 있습니다. Valid를 사용해도 동일하게 동작할 것이라고 생각되서 따로 추가하지 않았습니다.

2024-04-26 18:26 UTC, rookedsysc commented on src/test/java/com/gamemoonchul/application/PostOpenApiServiceTest.java
> +        for (int i = 1; i < searchedPost.size(); i++) {
혹시 코드 예시로 작성해주실 수 있으실까요? map 안에서 assert문을 작성할려고 보니 `Variable used in lambda expression should be final or effectively final`와 같은 에러가 발생합니다.

2024-04-26 18:27 UTC, rookedsysc commented on src/test/java/com/gamemoonchul/domain/entity/PostDummy.java
> +    public static Post createPost(String value) {
이 부분이 mock 클래스라고 생각하고 있었는데 혹시 슬빈님께서 생각하시는 mock 클래스는 어떤 클래스인가요?

2024-04-27 03:41 UTC, rookedsysc commented on src/test/java/com/gamemoonchul/application/PostOpenApiServiceTest.java
> +        for (int i = 1; i < searchedPost.size(); i++) {
혹시 이런식으로 말씀하시는걸까요?

```java
IntStream.range(1, searchedPost.size())
                    .allMatch(i -> searchedPost.get(i).getCreatedAt()
                        .isAfter(searchedPost.get(i - 1).getCreatedAt()))
```

2024-04-28 12:25 UTC, slbin-park approved these changes

2024-04-30 09:24 UTC, slbin-park approved these changes

2024-05-07 12:19 UTC, merged